# Service JavaFX
apiVersion: v1
kind: Service
metadata:
  name: javafx-service
  namespace: devops
spec:
  selector:
    app: javafx
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
