apiVersion: apps/v1
kind: Deployment
metadata:
  name: javafx-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javafx
  template:
    metadata:
      labels:
        app: javafx
    spec:
      containers:
        - name: javafx
          image: nginx:latest
          ports:
            - containerPort: 8080
