apiVersion: apps/v1
kind: Deployment
metadata:
  name: javafx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javafx
  template:
    metadata:
      labels:
        app: javafx
    spec:
      containers:
        - name: javafx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: javafx-service
spec:
  selector:
    app: javafx
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort

