apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-app-deployment
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: order-app
          image: workenx/order-app:latest
          imagePullPolicy: Always

          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "orderdb"
            - name: DB_USER
              value: "user"
            - name: DB_PASSWORD
              value: "password"
